name: image_hasher_dart
description: Package allowing creation of image hash that can be used to compare images for physical similarity.
version: 1.0.0
repository: https://github.com/KopaczPatryk/image_hasher_dart

environment:
  sdk: ^3.1.3

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5
  image: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^2.0.0
  test: ^1.21.0
